### ISSUE TITLE
Infinite Lignite and Sulfur Production

### ISSUE THREAD

**Issue by EndlessLeo** [enmumne/Gregorian-Nightmares#2]
Infinite lignite can be produced by a certain loop
![image](https://github.com/enmumne/Gregorian-Nightmares/assets/150091799/79b3522a-73fd-404f-8fee-a37257b5c52f)
![image](https://github.com/enmumne/Gregorian-Nightmares/assets/150091799/b7a80fd0-0e49-426c-800d-a237558d5b37)
![image](https://github.com/enmumne/Gregorian-Nightmares/assets/150091799/07e5d988-e838-43f0-a283-ec42068a4ee0)

**Comment by enmumne** [comment]
This one contains the fix here and for the other issue as well.

Had to increase the compressor 3 to 1, and reduce sulfur chance to 33% from 50%.

Math was somewhat cursed because it's still possible to loop the process again and again, but the ratios should make a bit more sense and it's not anymore an infinite loop...

[sprawl.zip](https://github.com/enmumne/Gregorian-Nightmares/files/14626643/sprawl.zip)
