### ISSUE TITLE
Mold Consumed Unexpectedly

### ISSUE THREAD

**Issue by EndlessLeo** [enmumne/Gregorian-Nightmares#3]
Ball mold was consumed when crafting glass tubes in a steam alloy smelter, while other molds were not consumed.
![image](https://github.com/enmumne/Gregorian-Nightmares/assets/150091799/83bd9804-8ce4-4247-a10b-2a72bc05ccb0)

**Comment by enmumne** [comment]
Fixed this internally. Would go into /kubejs/server_scripts/ and overwrite the "sprawl.js" file it contains.

I don't look often at this repository because I only use to dump scripts here once in a while.

Also trying to release an updated version, but waiting on a crash fix from Create that they've been sitting on for a whole week... I can't update until they do update as well.

[sprawl.zip](https://github.com/enmumne/Gregorian-Nightmares/files/14625855/sprawl.zip)
